/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  mauro
 * Created: 20-mag-2016
 */

CREATE TABLE Users
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(128) NOT NULL,
    password VARCHAR(128) NOT NULL,
    fname VARCHAR(128) NOT NULL,
    lname VARCHAR(128) NOT NULL,
    usertype BOOLEAN NOT NULL
);


CREATE TABLE Items
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    itemName VARCHAR(128) NOT NULL,
    description VARCHAR(1024),
    quantity INTEGER NOT NULL,
    price DOUBLE NOT NULL,
    img VARCHAR (1024),
    vendId INTEGER NOT NULL,
    FOREIGN KEY (vendId) REFERENCES Users(id)
);


CREATE TABLE Accounts
(
    userId INTEGER PRIMARY KEY NOT NULL,
    balance DOUBLE NOT NULL,
    FOREIGN KEY (userId) REFERENCES users(id)
);


INSERT INTO users (id, username, password, fname, lname, usertype)
VALUES (default, 'maurop', 'studente', 'Mauro', 'Puddu', false),
(default, 'kenf', 'scrittore', 'Ken', 'Follet', false),
(default, 'giannim', 'cantante', 'Gianni', 'Morandi', true),
(default, 'robertob', 'attore', 'Roberto', 'Benigni', true);

INSERT INTO Items (id, itemName, description, quantity, price, img, vendId)
VALUES (default, 'CANON P-215I - Scanner Portatile', 'Scanner ad alta definizione', 12,  239.99, 'img/canonp215.jpg', 0),
(default, 'ION Scanner Pics 2SD', 'Scanner ad alta definizione', 5, 140.09, 'img/ionscanner.jpg', 0),
(default, 'REFLECTA x8-Scan - Scanner per pellicole (35 mm) e diapositive', 'Scanner ad alta definizione', 3, 290.09, 'img/must.jpg', 0),
(default, 'PLUSTEK OpticSlim 1180 - Scanner piano A3', 'Scanner ad alta definizione', 1, 410.09, 'img/plustek.jpg', 1),
(default, 'MUST Scanner ScanExpress A4 USB 2400 Pro', 'Scanner ad alta definizione', 4, 200.09, 'img/reflectax8.jpg', 1);
 
INSERT INTO Accounts (userId, balance)
VALUES (1, 5879.79),
(2, 3863.00),
(3, 652.50),
(4, 152.60);